version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=mitienda
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mitienda_local
    volumes:
      - data-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
volumes:
  data-postgres:
